INFO:symExec:Totally 0 integrity policies
INFO:symExec:Totally 1 integrity policies
Traceback (most recent call last):
  File "../SpCon/spcon/symExec.py", line 682, in symExec
    SymExecEVM().symCreateContractAccount(contract=contract, EthereumAddress=EthereumAddress)
  File "../SpCon/spcon/symExec.py", line 573, in symCreateContractAccount
    logger.debug(f"symbolic contract_account: {hex(contract_account.address)}")
AttributeError: 'NoneType' object has no attribute 'address'
CRITICAL:symExec:AISPACE-0x6844ef18012a383c14e9a76a93602616ee9d6132 cannot be deployed using manticore
Traceback (most recent call last):
  File "../SpCon/spcon/symExec.py", line 682, in symExec
    SymExecEVM().symCreateContractAccount(contract=contract, EthereumAddress=EthereumAddress)
  File "../SpCon/spcon/symExec.py", line 573, in symCreateContractAccount
    logger.debug(f"symbolic contract_account: {hex(contract_account.address)}")
AttributeError: 'NoneType' object has no attribute 'address'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../SpCon/spcon/__main__.py", line 36, in execute_command
    SymExecEVM().fuzzing(contract=contractName, EthereumAddress=args.eth_address, separation_policies = separation_policies, integrity_policies=integrity_policies,\
  File "../SpCon/spcon/symExec.py", line 748, in fuzzing
    attack_test_sequence = greedyTesting(data, S=Stack, unauthorizedusers = unauthorizedusers, desc=f"Testing separation priviledgefuncs...\nR: {authorizedrole[1]}\n")
  File "../SpCon/spcon/symExec.py", line 706, in greedyTesting
    if not symExec(unauthorizedusers, S):
  File "../SpCon/spcon/symExec.py", line 686, in symExec
    exit(-1)
  File "../anaconda3/envs/spcon/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: -1
Traceback (most recent call last):
  File "../SpCon/spcon/symExec.py", line 682, in symExec
    SymExecEVM().symCreateContractAccount(contract=contract, EthereumAddress=EthereumAddress)
  File "../SpCon/spcon/symExec.py", line 573, in symCreateContractAccount
    logger.debug(f"symbolic contract_account: {hex(contract_account.address)}")
AttributeError: 'NoneType' object has no attribute 'address'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../SpCon/spcon/__main__.py", line 36, in execute_command
    SymExecEVM().fuzzing(contract=contractName, EthereumAddress=args.eth_address, separation_policies = separation_policies, integrity_policies=integrity_policies,\
  File "../SpCon/spcon/symExec.py", line 748, in fuzzing
    attack_test_sequence = greedyTesting(data, S=Stack, unauthorizedusers = unauthorizedusers, desc=f"Testing separation priviledgefuncs...\nR: {authorizedrole[1]}\n")
  File "../SpCon/spcon/symExec.py", line 706, in greedyTesting
    if not symExec(unauthorizedusers, S):
  File "../SpCon/spcon/symExec.py", line 686, in symExec
    exit(-1)
  File "../anaconda3/envs/spcon/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: -1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../SpCon/spcon/__main__.py", line 73, in main
    execute_command(args)
  File "../SpCon/spcon/__main__.py", line 41, in execute_command
    raise Exception("Unkown error")
Exception: Unkown error
